ALTER TABLE users
ADD COLUMN IF NOT EXISTS default_location TEXT;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS default_latitude DOUBLE PRECISION;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS default_longitude DOUBLE PRECISION;

ALTER TABLE shoppers
ADD COLUMN IF NOT EXISTS approved BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS delivery_latitude DOUBLE PRECISION;

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS delivery_longitude DOUBLE PRECISION;

CREATE TABLE IF NOT EXISTS volunteer_thanks (
    thanks_id SERIAL PRIMARY KEY,
    order_id INT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    customer_user_id INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    shopper_user_id INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
